import {flags} from '@oclif/command'
import {StackCommand} from '../../lib/commands/stack-command'
import {matchingJobIds, promptUserForJobId} from '../../lib/functions/run-functions'
import {printResultState} from '../../lib/functions/misc-functions'

export default class Log extends StackCommand {
  static description = 'Print any output generated by a job.'
  static args = [{name: 'id'}]
  static flags = {
    stack: flags.string({env: 'STACK'}),
    explicit: flags.boolean({default: false}),
    lines: flags.string({default: "100"})
  }
  static strict = true;

  async run()
  {
    const {argv, flags} = this.parse(Log)
    const runner  = this.newRunner(flags.explicit)
    // get id and stack_path
    var stack_path = (flags.stack) ? this.fullStackPath(flags.stack) : ""
    var id = argv[0] || await promptUserForJobId(runner, stack_path, "", !this.settings.get('interactive')) || ""
    // match with existing container ids
    var result = matchingJobIds(runner, id, stack_path)
    if(result.success)runner.jobLog(result.data[0], flags.lines)
    printResultState(result)
  }

}
